pipeline:
  install:
    image: node:latest
    commands:
      - npm install
  build:
    image: node:latest
    commands:
      - npm run build
  test:
    image: node:latest
    commands: npm run lint
